# Generated by Django 3.0.3 on 2020-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='browser',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
