# Generated by Django 3.0.3 on 2020-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200426_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='browser',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
